name: Update github myprofile

on: 'page_build'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools
    - name: Run
      run: |
        cd ./github_myprofile_updater
        python3 update.py
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "shengmingkai22@mails.ucas.ac.cn"
        echo "${GITHUB_ACTOR}"
        echo "${{ secrets.GHRS_GITHUB_API_TOKEN }}"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GHRS_GITHUB_API_TOKEN }}@github.com/MingkaiSheng/MingkaiSheng.git"
        echo "${remote_repo}"
        git add README.md
        git add images
        git commit -m "update my description automatically"
        git push "${remote_repo}" HEAD:main --force
